# Generated by Django 5.2.4 on 2025-08-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Job_role', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Department', models.TextField()),
                ('Date_Of_Joining', models.DateField()),
            ],
        ),
    ]
